//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensorDiagnosticTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SensorDiagnosticTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1.
        /// </summary>
        internal static string Address1 {
            get {
                return ResourceManager.GetString("Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        internal static string Address2 {
            get {
                return ResourceManager.GetString("Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        internal static string Altitude {
            get {
                return ResourceManager.GetString("Altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude Error.
        /// </summary>
        internal static string AltitudeError {
            get {
                return ResourceManager.GetString("AltitudeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CivicAddress.
        /// </summary>
        internal static string CivicAddress {
            get {
                return ResourceManager.GetString("CivicAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country/Region.
        /// </summary>
        internal static string CountryRegion {
            get {
                return ResourceManager.GetString("CountryRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Updated event for sensor {0}.
        /// </summary>
        internal static string DataUpdatedEventUI {
            get {
                return ResourceManager.GetString("DataUpdatedEventUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Location Provider.
        /// </summary>
        internal static string DefaultLocationProvider {
            get {
                return ResourceManager.GetString("DefaultLocationProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Level.
        /// </summary>
        internal static string DetailLevel {
            get {
                return ResourceManager.GetString("DetailLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter event for sensor {0}.
        /// </summary>
        internal static string EnterEventUI {
            get {
                return ResourceManager.GetString("EnterEventUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter event for sensor {0}.
        /// </summary>
        internal static string EnterEventXML {
            get {
                return ResourceManager.GetString("EnterEventXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Radius.
        /// </summary>
        internal static string ErrorRadius {
            get {
                return ResourceManager.GetString("ErrorRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string ErrorString {
            get {
                return ResourceManager.GetString("ErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing.
        /// </summary>
        internal static string Initializing {
            get {
                return ResourceManager.GetString("Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LatLong.
        /// </summary>
        internal static string LatLong {
            get {
                return ResourceManager.GetString("LatLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave event for sensor {0}.
        /// </summary>
        internal static string LeaveEventUI {
            get {
                return ResourceManager.GetString("LeaveEventUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave event for sensor {0}.
        /// </summary>
        internal static string LeaveEventXML {
            get {
                return ResourceManager.GetString("LeaveEventXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Changed event received.
        /// </summary>
        internal static string LocationChangedEventUI {
            get {
                return ResourceManager.GetString("LocationChangedEventUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Status Changed event received, status changed to {0}.
        /// </summary>
        internal static string LocationStatusChangedEventUI {
            get {
                return ResourceManager.GetString("LocationStatusChangedEventUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Status Changed event for location to status {1}.
        /// </summary>
        internal static string LocationStatusChangedEventXML {
            get {
                return ResourceManager.GetString("LocationStatusChangedEventXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data.
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entries.
        /// </summary>
        internal static string NoEntries {
            get {
                return ResourceManager.GetString("NoEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        internal static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Status.
        /// </summary>
        internal static string ReportStatus {
            get {
                return ResourceManager.GetString("ReportStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor ID.
        /// </summary>
        internal static string SensorID {
            get {
                return ResourceManager.GetString("SensorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SensorLog.
        /// </summary>
        internal static string SensorLogFileName {
            get {
                return ResourceManager.GetString("SensorLogFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files.
        /// </summary>
        internal static string SensorLogFilterText {
            get {
                return ResourceManager.GetString("SensorLogFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors.
        /// </summary>
        internal static string Sensors {
            get {
                return ResourceManager.GetString("Sensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Changed event for sensor {0} to state {1}.
        /// </summary>
        internal static string StateChangedEventUI {
            get {
                return ResourceManager.GetString("StateChangedEventUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} State Changed event to state {1}.
        /// </summary>
        internal static string StateChangedEventXML {
            get {
                return ResourceManager.GetString("StateChangedEventXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/Province.
        /// </summary>
        internal static string StateProvince {
            get {
                return ResourceManager.GetString("StateProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string StringUI {
            get {
                return ResourceManager.GetString("StringUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string StringXML {
            get {
                return ResourceManager.GetString("StringXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip/Postal code.
        /// </summary>
        internal static string ZipPostalCode {
            get {
                return ResourceManager.GetString("ZipPostalCode", resourceCulture);
            }
        }
    }
}
